### ISSUE TITLE
2023.05.20: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by wuch-g2v** [pradyunsg/furo#665]
### What's happening?

First of all currently it is not possible to use straight `sphinx-build` command to build documentation out of source tree
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.1

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 442, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'furo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 229, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 404, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 445, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension furo.sphinxext (exception: No module named 'furo')

Extension error:
Could not import extension furo.sphinxext (exception: No module named 'furo')
```
</details>

This can be fixed by patch like below:
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -7,6 +7,8 @@
 import sys
 from typing import Any, Dict

+sys.path.insert(0, os.path.abspath("../src"))
+
 # add the demo python code to the path, so that it can be used to demonstrate
 # source links
 sys.path.append(os.path.abspath("./kitchen-sink/demo_py"))
```

This patch bases on sphinx example copy.py https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

Than .. on building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.

Here is the output with warnings:
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.1
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
myst v1.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'colon_fence', 'deflist'}, disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=3, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 44 added, 0 changed, 0 removed
reading sources... [100%] stability
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-furo.3 { quickstart customisation/index customisation/logo customisation/announcement customisation/edit-button customisation/colors customisation/fonts customisation/footer customisation/landing-page customisation/sidebar customisation/sidebar-title customisation/toc customisation/injecting reference/index reference/text-formatting reference/admonitions reference/api reference/code-blocks reference/hyperlinks reference/images reference/lists reference/tables reference/tabs recommendations contributing/index contributing/workflow contributing/internals contributing/design kitchen-sink/index kitchen-sink/admonitions kitchen-sink/api kitchen-sink/blocks kitchen-sink/generic kitchen-sink/images kitchen-sink/lists kitchen-sink/really-long kitchen-sink/sphinx-design kitchen-sink/structure kitchen-sink/tables kitchen-sink/typography stability changelog license } /usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:20: WARNING: py:class reference target not found: urllib3.exceptions.MaxRetryError
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:1: WARNING: py:class reference target not found: iterable
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:83: WARNING: py:attr reference target not found: Retry.DEFAULT_ALLOWED_METHODS
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:1: WARNING: py:class reference target not found: iterable
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:108: WARNING: py:func reference target not found: sleep
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:108: WARNING: py:attr reference target not found: Retry.DEFAULT_BACKOFF_MAX
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:123: WARNING: py:meth reference target not found: Retry.increment
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:123: WARNING: py:class reference target not found: RequestHistory
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:128: WARNING: py:attr reference target not found: Retry.RETRY_AFTER_STATUS_CODES
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:1: WARNING: py:class reference target not found: iterable
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry.increment:5: WARNING: py:class reference target not found: urllib3.response.HTTPResponse
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.clone:7: WARNING: py:class reference target not found: Timeout
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.connect_timeout:7: WARNING: py:attr reference target not found: Timeout.DEFAULT_TIMEOUT
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.from_float:3: WARNING: py:class reference target not found: Timeout
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.from_float:1: WARNING: py:class reference target not found: integer
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.from_float:1: WARNING: py:class reference target not found: sentinel default object
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.from_float:11: WARNING: py:class reference target not found: Timeout
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.get_connect_duration:1: WARNING: py:meth reference target not found: start_connect
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.get_connect_duration:1: WARNING: py:exc reference target not found: urllib3.exceptions.TimeoutStateError
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.read_timeout:6: WARNING: py:exc reference target not found: urllib3.exceptions.TimeoutStateError
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.read_timeout:12: WARNING: py:attr reference target not found: Timeout.DEFAULT_TIMEOUT
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.read_timeout:1: WARNING: py:exc reference target not found: urllib3.exceptions.TimeoutStateError
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.read_timeout:13: WARNING: py:meth reference target not found: start_connect
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.start_connect:1: WARNING: py:exc reference target not found: urllib3.exceptions.TimeoutStateError
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:20: WARNING: py:class reference target not found: urllib3.exceptions.MaxRetryError
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:1: WARNING: py:class reference target not found: iterable
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:83: WARNING: py:attr reference target not found: Retry.DEFAULT_ALLOWED_METHODS
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:1: WARNING: py:class reference target not found: iterable
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:108: WARNING: py:func reference target not found: sleep
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:108: WARNING: py:attr reference target not found: Retry.DEFAULT_BACKOFF_MAX
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:123: WARNING: py:meth reference target not found: Retry.increment
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:123: WARNING: py:class reference target not found: RequestHistory
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:128: WARNING: py:attr reference target not found: Retry.RETRY_AFTER_STATUS_CODES
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry:1: WARNING: py:class reference target not found: iterable
/usr/lib/python3.8/site-packages/urllib3/util/retry.py:docstring of urllib3.util.retry.Retry.increment:5: WARNING: py:class reference target not found: urllib3.response.HTTPResponse
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.clone:7: WARNING: py:class reference target not found: Timeout
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.connect_timeout:7: WARNING: py:attr reference target not found: Timeout.DEFAULT_TIMEOUT
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.from_float:3: WARNING: py:class reference target not found: Timeout
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.from_float:1: WARNING: py:class reference target not found: integer
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.from_float:1: WARNING: py:class reference target not found: sentinel default object
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.from_float:11: WARNING: py:class reference target not found: Timeout
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.get_connect_duration:1: WARNING: py:meth reference target not found: start_connect
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.get_connect_duration:1: WARNING: py:exc reference target not found: urllib3.exceptions.TimeoutStateError
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.read_timeout:6: WARNING: py:exc reference target not found: urllib3.exceptions.TimeoutStateError
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.read_timeout:12: WARNING: py:attr reference target not found: Timeout.DEFAULT_TIMEOUT
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.read_timeout:1: WARNING: py:exc reference target not found: urllib3.exceptions.TimeoutStateError
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.Timeout.read_timeout:13: WARNING: py:meth reference target not found: start_connect
/usr/lib/python3.8/site-packages/urllib3/util/timeout.py:docstring of urllib3.util.timeout.Timeout.start_connect:1: WARNING: py:exc reference target not found: urllib3.exceptions.TimeoutStateError
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/blocks.rst:106: WARNING: 'token' reference target not found: suite
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/blocks.rst:106: WARNING: 'token' reference target not found: expression
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/blocks.rst:106: WARNING: 'token' reference target not found: target
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/blocks.rst:106: WARNING: 'token' reference target not found: suite
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/blocks.rst:106: WARNING: 'token' reference target not found: suite
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/blocks.rst:106: WARNING: 'token' reference target not found: suite
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/blocks.rst:106: WARNING: 'token' reference target not found: suite
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/blocks.rst:106: WARNING: 'token' reference target not found: suite
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/generic.rst:42: WARNING: py:class reference target not found: api_sample.RandomNumberGenerator
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/customisation/toc.md:7: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/customisation/toc.md:15: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/text-formatting.md:6: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/text-formatting.md:43: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/admonitions.md:8: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/admonitions.md:37: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/admonitions.md:36: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/admonitions.md:63: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/admonitions.md:139: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/admonitions.md:178: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/admonitions.md:205: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/admonitions.md:228: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/api.md:8: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/api.md:35: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/code-blocks.md:6: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/code-blocks.md:57: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/hyperlinks.md:6: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/hyperlinks.md:33: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/images.md:8: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/images.md:23: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/images.md:22: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/images.md:41: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/images.md:40: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/images.md:59: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/images.md:68: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/images.md:99: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/lists.md:8: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/lists.md:39: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/lists.md:37: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/lists.md:50: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/lists.md:50: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/lists.md:69: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tables.md:6: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tables.md:: WARNING: "table cell spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tables.md:: WARNING: "table row spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tables.md:: WARNING: "table row spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tables.md:: WARNING: "table cell spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tables.md:67: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tabs.md:12: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tabs.md:26: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tabs.md:30: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tabs.md:35: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tabs.md:46: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tabs.md:50: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tabs.md:38: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/reference/tabs.md:65: WARNING: "unsupported "label"
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/tables.rst:: WARNING: "table cell spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/tables.rst:: WARNING: "table row spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/tables.rst:: WARNING: "table row spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/tables.rst:: WARNING: "table cell spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/tables.rst:: WARNING: "table cell spanning" not supported
/home/tkloczko/rpmbuild/BUILD/furo-2023.05.20/docs/kitchen-sink/tables.rst:: WARNING: "table cell spanning" not supported
done
build succeeded, 109 warnings.
```
</details>

You can peak on fixes that kind of issues in other projects
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/frostming/unearth/issues/14
https://github.com/jaraco/cssutils/issues/21
https://github.com/latchset/jwcrypto/pull/289
https://github.com/latchset/jwcrypto/pull/289
https://github.com/pypa/distlib/commit/98b9b89f
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/sqlalchemy/sqlalchemy/commit/5e88e6e8

### Reproducer

Just run `/usr/bin/sphinx-build -n -T -b man docs build/sphinx/man` in root source tree.

### Expectation

sphinx should not generate warninx with `-n` option.

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by Eric-Arellano** [comment]
Hey, I believe this should not be related to Furo. Sphinx separates out "content" from "presentation". What happens if you change `html_theme = "alabaster"`, i.e. one of the builtin themes.

**Comment by wuch-g2v** [comment]
Those warnings are about references incorrectly defined,
As you see I'm generating man page to show you that it has nothing to do with theme.

**Comment by pradyunsg** [comment]
Generating man pages is something I recommend that you do not try; that's not something that I expect to be necessary for an HTML theme. If you're using this *website* theme, it is expected that you'll be able to use a browser.

Beyond that, https://github.com/pradyunsg/furo/blob/490527b2aef00b1198770c3389a1979911ee1fcb/noxfile.py#L68 for how to build the documentation of this theme.

The errors and nitpicks are because you aren't installing things that need to be installed in the documentation build environment.

Finally, this is _not_ a "trackable task" for the project, which is the template used to file this issue. You've explicitly ignored "Please only use this, if you've been advised to do so after discussion." that was in the issue template selection page, which is not appreciated on my end.

**Comment by pradyunsg** [comment]
I'll also point out that you could have figured out what the right thing to do here would be by reading https://pradyunsg.me/furo/contributing/workflow/#documentation-generation, which is the documentation of this project and linked to from multiple places.

**Comment by pradyunsg** [comment]
Hmm... @wuch-g2v looks like a sock-puppet account for @kloczek, to circumvent direct blocking? The issues filed have the exact same style (and level of ignorance of written instructions + lack of research) as that user, and looking at the user's history, they've only filed issues in repositories where I know @kloczek is banned from interacting.

**Comment by pradyunsg** [comment]
_sigh_

Yes, it is. From https://github.com/seleniumbase/SeleniumBase/issues/1899:

```
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-seleniumbase-4.14.14-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-seleniumbase-4.14.14-2.fc
```

**Comment by pradyunsg** [comment]
1. You've put no effort into looking at the project documentation.
2. You've actively attempted to engage with someone who has blocked you, and proactively engaged in ban evasion (from https://discourse.nixos.org/t/github-block-evasion-is-not-acceptable/12763, "Forcing people to continue engaging [after they've blocked you] is a form of harassment"). 
3. You've ignored instructions provided in the template selection screen about how to engage with the project.
4. What you're reporting is bogus, and you could have figured that out by spending less than 5 minutes looking at the project (especially, given that you've now interacted with a large portion of the Python ecosystem.

**Comment by wuch-g2v** [comment]
Again. I'm working with person which you've blocked.

Incorrect references exposed by `-n` option are affecting html, qch and pdf output.
We are providing as general feedback what has been found during use our packaging procedure. If you want to ignore that issue that is perfectly fine as on packaging python modules used out approach is generated roff output out packages are not affected by what has been reported.
Reported issue is not critical by any meaning.

If want to punish messenger that is a bit odd ..
Ticket has been closed. Maintainer has been informed about that issue. That was my goal.
Everything else is out of the scope of this ticket.

**Comment by pradyunsg** [comment]
_sigh_

I hope that you'd be willing to do any amount of self-reflection and understand what I'm trying to tell you.

Tomasz, please read project documentation for instructions and investigate the issue yourself **before** asking the project to investigate by filing issues, follow the contribution process of the project you're interacting with, and don't create sock puppets to circumvent bans.

We're done here.
